"""Añadir campos de verificacion a AuditoriaPago

Revision ID: 79c01035e3b8
Revises: 001_agregar_campos_verificacion
Create Date: 2025-11-25 18:04:43.886226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c01035e3b8'
down_revision = '001_agregar_campos_verificacion'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verificado', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fecha_verificacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.alter_column('email_verificado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('rol')
        batch_op.drop_column('fecha_verificacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_verificacion', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('rol', sa.VARCHAR(length=20), server_default=sa.text('("usuario")'), nullable=False))
        batch_op.alter_column('email_verificado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('auditoria_pago', schema=None) as batch_op:
        batch_op.drop_column('fecha_verificacion')
        batch_op.drop_column('email_verificado')

    # ### end Alembic commands ###
