"""Agregar fecha_creacion y ultimo_acceso

Revision ID: b75a902e792b
Revises: 
Create Date: 2025-11-19 03:28:43.092260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75a902e792b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ultimo_acceso', sa.DateTime(), nullable=True))

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('fecha_fin',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('cuenta', schema=None) as batch_op:
        batch_op.drop_column('ultimo_acceso')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
